django_rest_framework/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('drfapp.urls' , 'drfapp'), namespace='main_url')),
    path('api-auth/', include('rest_framework.urls')),
]

drfapp/api/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import ArticleViewSet, AuthorProfileViewSet
from.import views
from rest_framework.routers import DefaultRouter, SimpleRouter 

router = DefaultRouter()
router.register('Article', ArticleViewSet, basename='router_register_drfapp')

router.register('AuthorProfile', AuthorProfileViewSet, basename='AuthorProfile')


urlpatterns = [
       path('api/', include((router.urls, 'drfapp'), namespace='api_folder_urls')),
]

drfapp/urls.py
from django.contrib import admin
from django.urls import path, include
from drfapp.views import *
from.import views


 


urlpatterns = [
    path('api/', include(('drfapp.api.urls', 'drfapp'), namespace='drfapp_url')),
    path('Article/', views.get_article, name="article"),
    
    #test 
    path('article_test/', views.test_template, name="article"), 
    path('home_test/', views.home, name="blog_home_url"),
    path('about_test/', views.about, name="blog_about_url"),
]

drfapp/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):
	created_by     = models.ForeignKey(User,null=True, on_delete=models.CASCADE)
	content        = models.TextField()
	created_date   = models.DateTimeField(auto_now=False,auto_now_add=True)

	def __str__(self):

		return str(self.created_by)

	def clean(self):
		number = self.content
		if len(number)<5:
			raise ValidationError("plz 5 up Character")
		else:
		   print('Better')	


     
class AuthorProfile(models.Model):
	user          = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
	profile_image = models.ImageField()
	first_name    = models.CharField(max_length=200)
	last_name     = models.CharField(max_length=200)


	def __str__(self):

		return str(self.first_name)

drfapp/api/views.py
from django.shortcuts import render, get_object_or_404
from rest_framework import viewsets, permissions
from drfapp.models import *
from .serializers import ArticleSerializers, AuthorProfileSerializers
from .pagination import PostLimitOffsetPagination, PostPageNumberPagination 
from django.db.models import Q
from django_filters import rest_framework as filters
from .permissions import ArticlePermission, AuthorProfilePermission



# from rest_framework.filters import(
# 	SearchFilter, 
# 	OrderingFilter
# 	)


class AuthorProfileViewSet(viewsets.ModelViewSet):
	queryset = AuthorProfile.objects.all()
	serializer_class = AuthorProfileSerializers
	permission_classes = [AuthorProfilePermission,]


class ArticleFilter(filters.FilterSet):
	#content = filters.CharField(lookup_expr='icontains')

	class Meta:
		model = Article
		fields = {
		'content':['icontains'],
		'created_by__username':['icontains'],
		}



class ArticleViewSet(viewsets.ModelViewSet):
	queryset  = Article.objects.all()
	serializer_class = ArticleSerializers
	#pagination_class = PostPageNumberPagination
	filterset_class = ArticleFilter
	#permission_classes = [ArticlePermission,]
	#permission_classes = [permissions.IsAuthenticated,]

drfapp/views.py
from django.shortcuts import render, HttpResponse
from drfapp.models import Article

def get_article(request):
	
	return render(request, 'home_page.html')
   
 



def test_template(request):
	queryset = Article.objects.all()
	context = {
	  "var1":None,
	  "var2":None,
	  "queryset":queryset

	}
	return render(request, 'article_update.html', context)





def home(request):
	blog = Article.objects.all()
	context ={
	   'blog':blog,
	}
	return render(request, "tutorial/home.html", context)


def about(request):
	return render(request, "tutorial/about.html", {"title":'About'})

	# filter_backends = [SearchFilter]
	# search_fields = ['content', 'created_by__first_name']

	# def get_queryset(self, *args, **kwargs):
	# 	queryset  = Article.objects.all()
	# 	query  = self.request.GET.get('q')
	# 	if query:
	# 		queryset=queryset.filter(
 #                Q(content__icontains=query)
	# 			).distinct()

	# 	return queryset


	# def get_queryset(self):
	# 	return Article.objects.filter(created_by=self.request.user)

	
   
    # Filtering against the URL
	# def get_queryset(self):
	# 	username = self.kwargs['username']
	# 	return Article.objects.filter(created_by=username)
	#  

templates/article_update.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">
    <script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js'%}"></script>
<style type="text/css">
  <style>
   .row1 {
      background: #345678;
   }
   .row2 {
      background: #123456;
   }
</style>
</style>
</head>
<body>
   <!-- {% for i in queryset %}
    {{ i.content|lower }}
    {{ i.content|upper }}
   content {{ i.content|filesizeformat }}
    {{ i.created_date|date:"Y-m-d" }}
    {% if i.content|length > 7 %}
      <h4>{{ i.content }}</h4>

      {% else %}
      <h4>ok man</h4>
      {% endif %}
    {% endfor %} -->
    
    <!-- {% for i in queryset %}
     {{ i.created_date|date:"d M Y"}}
    {% endfor %} -->

    <!-- {% for i in queryset %}
    <tr>
    <td class="{% cycle 'row1' 'row2' as rowcolors %}">{{ i.created_by.username }}</td>
    <td class="{{ rowcolors }}">{{ i.content }}</td>
    </tr>
<tr>
  <td class="{% cycle rowcolors %}">{{ i.created_date|date:'d M Y' }}</td>
  <td class="{{ rowcolors }}"></td>
</tr>
   
    {% endfor %}
   -->

  {# django test project #}
 

<!-- {% firstof var1 var2 queryset as value %} -->
 
<!-- {% for i in queryset %} 
{% if not i %}
  <h4>not queryset</h4>
{% else %} 
   {% if 'alamin' in i.content %}
    <h4>success</h4>
    {% else %}
      {% if i.content|length > 10 %}
      <h4>length check</h4>
      {% else %}
        <h4>Length not support</h4>
      {% endif %}
    {% endif %}
{% endif %}

{% empty %}
<h4>no data </h4>

{% endfor %} -->



<!-- {% for i in queryset %}
  <div style="background-color:
        {% ifchanged i.content %}
            {% cycle 'red' 'blue' %}
        {% else %}
            gray
        {% endifchanged %}
    ">{{ i.content }}</div>
{% endfor %} -->


 <!-- <p>{{ i.content|capfirst }}</p> -->
<!-- <p>{{ i.content|add:'2' }}</p> -->
<!-- <p>"{{ i.content|center:"15" }}"</p> -->
<!-- <p>{{ i.content|cut:" " }}</p> -->


<!-- It is {% now "jS F Y H:i" %}
It is the {% now "jS \o\f F" %}

 -->


</body>
</html>

templates/home_page.html
<!DOCTYPE html>
{% load static %}
{% load widget_tweaks %}
<html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css'%}">

    <script type="text/javascript" src="{% static 'js/jquery.js'%}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.min.js'%}"></script>


</head>
<body>



 


  <table class="table table-bordered simple-table">
    <tr>
    <th>#</th>
    <th>Eamil</th>
    <th>Content</th>
    <th>Created_date</th>
    <th></th>
    <th></th>
    </tr>
  <tr>
     
     
  </tr>
  </table>
  home page
  <br>
  <br>
  <div class="container">
    <form method="POST" id="article_form" action="">
      {% csrf_token %}
      <textarea name="content" id="content"></textarea>
      <button id="button" class="btn btn-success">submit</button>
   </form> 
</div>
  <br>
  <br>
  <div class="test">
   <br>
  </div>
<script type="text/javascript">
  // var  get_update_csrf = '{{ csrf_token }}'
  // var url ="{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  // console.log(url);
  // $.ajax({
  //     url:url,
  //     type:'GET',
  //     data:'json',
  //     success:function(data){
  //       if(data.length > 0){
  //         $.each(data, function(i, item){
  //          // $('.test').append("<span class='show1'>"+ data[i].created_by.email +"</span")
  //          // $('.test').append("<span class='show2'>"+ data[i].content +"</span")
  //          // $('.test').append("<span class='show3'>"+ data[i].created_date +"</span")
  //          $('.test').append("<button data-url='' data-id= "+ data[i].id +" class='delete' >Delete</span")
  //          console.log(data[i].id);
  //         })
          
  //       }else{
  //           console.log(data);
  //         }
  //     }
  // });

// $(document).on('click', '.delete', function(){
//     var contentid = $(this).attr('data-id');
//     console.log(contentid);
//     var deleteid = this_delete_fun(contentid);
//     console.log(deleteid);
//     $('.delete').attr('data-url',deleteid);

//     url = $(this).attr('data-url');
//     console.log(url);
//     $.ajax({
//       url:url,
//       type:'DELETE',
//       beforeSend:function(xhr){
//           xhr.setRequestHeader("X-CSRFToken", get_update_csrf);
//         },
//       success:function(){
//          alert('success');
//         }
//   })
// });

// var this_delete_fun =function(id){
//      var leave_api_obj = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-detail' '0' %}"
//         leave_api_obj = leave_api_obj.slice(0,-2)    //to remove demo value '0' from ur
//         leave_api_obj = leave_api_obj + id +'/'
//         return leave_api_obj    
//     }

 

</script>




  <div class="article_show">
  </div>
    <br>
   
    <div class="inputform">
      <form id="article_form" method="POST" class="article-form">
        {% csrf_token %}
        <textarea name="content" class='content'></textarea>
        <a id="button" data-url='' class="btn btn-success submit" type="submit">Update</a>
      </form> 
    </div>
<script type="text/javascript">
  // --------------------POST------------------
  var url = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  console.log(url)
  $(document).on('submit', "#article_form", function(e){
  e.preventDefault();
  var articleForm =$(this);
  var articleFormData = new FormData(articleForm[0]);
  $.ajax({
    type: "POST",
    url : url,
    data: articleFormData,
    async:true,
    contentType:false,
    processData:false,
    cache:false,
     success:function(data){
      alert('success');

     }
  });
});

  var  get_update_csrf = '{{ csrf_token }}'
  $(document).ready(function(){
  var url = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  console.log(url)

     $.ajax({
      url:url,
      type:'GET',
      data:'json',

      success: function (data){ 
        if(data.length > 0) {
         $.each(data, function(i, item){

 $(".simple-table").append("<tr><td>"+data[i].id+"</td><td>"+data[i].created_by.email+"</td><td>"+data[i].content+"</td><td>"+data[i].created_date+"</td><td>"+("<button data-content="+ data[i].content +" data-id="+ data[i].id +" class='show3'>update</button>")+"</td><td>"+("<button data-url='' data-id= "+ data[i].id +" class='delete' >Delete</span")+"</td></tr>");

 
         
        
           
           })
        } else{
           console.log(data); 
            
        }  
      },
     });
// -------------updated------------------------
$(document).on('click', '.show3', function(){ 
    data = $(this).attr('data-content');
    $(".content").val(data);
    console.log(data);
    data = $(this).attr('data-id');
    url = this_content_fun(data)
    $(".submit").attr('data-url', url);
    console.log(url);
  })

  });


   var this_content_fun =function(id){
     var leave_api_obj = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-detail' '0' %}"
        leave_api_obj = leave_api_obj.slice(0,-2)    //to remove demo value '0' from ur
        leave_api_obj = leave_api_obj + id +'/'
        return leave_api_obj    
    }


    $(document).on('click', '.submit', function(){
     event.preventDefault();
     var url = $(this).attr('data-url');
     var form = $(".article-form").serialize()
     console.log("data==", form)
     $.ajax({
      type: "PUT",
      url : url,
      data: form,
      beforeSend:function(xhr){
        xhr.setRequestHeader("X-CSRFToken", get_update_csrf);
      },
     
       success:function(data){
        alert('success');
       },
       error:function(data){
        console.log(data)
       }
    });
      
    });

   // ----------------delete method---------------- 
   var this_delete_fun =function(id){
     var leave_api_obj = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-detail' '0' %}"
        leave_api_obj = leave_api_obj.slice(0,-2)    //to remove demo value '0' from ur
        leave_api_obj = leave_api_obj + id +'/'
        return leave_api_obj    
    } 
   $(document).on('click', '.delete', function(){
    var contentid = $(this).attr('data-id');
    console.log(contentid);
    var deleteid = this_delete_fun(contentid);
    console.log(deleteid);
    $('.delete').attr('data-url',deleteid);

    url = $(this).attr('data-url');
    console.log(url);
    $.ajax({
      url:url,
      type:'DELETE',
      beforeSend:function(xhr){
          xhr.setRequestHeader("X-CSRFToken", get_update_csrf);
        },
      success:function(){
         alert('success');
        }
  })
});



</script>

<!-- <div class="container">
    <form method="POST" id="article_form" action="">
      {% csrf_token %}
      <textarea name="content" id="content"></textarea>
      <button id="button" class="btn btn-success">submit</button>
   </form> 
</div> -->

<!-- <script type="text/javascript">
  $(document).ready(function(){
  var url = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  console.log(url)
   $('button').click(function(){
     $.ajax({
      url:url,
      type:'GET',
      data:'json',

      success: function (data){ 
        if(data.length > 0) {
         $.each(data, function(i, item){
          $(".article_show").append("<div class='show'>"+ data[i].content +"</div>");
          $(".article_show").append("<div class='show1'>"+ data[i].created_by.email +"</div>");
          $(".article_show").append("<div class='show2'>"+ data[i].created_date +"</div>");

          console.log(data);
          console.log(data[i].id);
          console.log(data[i].content);
          console.log(data[i].created_by.last_name);
          console.log(data[i].created_date);

           })
        } else {
           console.log(data); 
            
        }
         
      },
         

      error:function(djqXHR, exception){
        console.log(djqXHR);
        console.log(exception);
      }

     });
   });
  });
</script> -->


<!-- <script type="text/javascript">
  var url = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  console.log(url)
  $.ajax({
    url:url,
    type:'GET',
    data:'json',
    success:function(data){
      console.log(data);
    },

    error:function(djqXHR, exception){
      console.log(djqXHR);
      console.log(exception);
    }
  });
</script> -->



<!-- <script type="text/javascript">
  var url = "{% url 'main_url:drfapp_url:api_folder_urls:router_register_drfapp-list' %}"
  console.log(url)
  $(document).on('submit', "#article_form", function(e){
  e.preventDefault();
  var articleForm =$(this);
  var articleFormData = new FormData(articleForm[0]);
  $.ajax({
    type: "POST",
    url : url,
    data: articleFormData,
    async:true,
    contentType:false,
    processData:false,
    cache:false,
     success:function(data){
      alert('success');

     }
  });
});
</script>
 -->
</body>
</html>

templates/tutorial/about.html
{% extends 'tutorial/base.html' %}
{% block content %}
 <h3> About Page </h3>
{% endblock %}

templates/tutorial/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/main.css' %}">
    {% if title %}
	<title>Title {{ title }}</title>
	{% else %}
	<title>No Title</title>
	{% endif %}
</head>
<body>
	<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
        <a class="navbar-brand mr-4" href="{% url 'main_url:blog_home_url' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'main_url:blog_home_url' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'main_url:blog_about_url' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Login</a>
              <a class="nav-item nav-link" href="#">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">

        <div class="col-md-8">
          {% block content %}{% endblock %}
        </div>

        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>
	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>

templates/tutorial/header.html
<header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blog-home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'blog-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'blog-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              <a class="nav-item nav-link" href="#">Login</a>
              <a class="nav-item nav-link" href="#">Register</a>
            </div>
          </div>
        </div>
      </nav>
    </header>

templates/tutorial/home.html
{% extends "tutorial/base.html" %}
{% block content %}
	{% for i in blog %}
	   <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ i.created_by.username }}</a>
              <small class="text-muted">{{ i.created_date }}</small>
            </div>
            
            <p class="article-content">{{i.content }}</p>
          </div>
        </article>
	{% endfor %}
{% endblock %}